inherit_from: .rubocop_todo.yml

require:
 - rubocop-rake
 - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Layout/LineLength:
  Max: 100

NestedGroups:
  Max: 5

RSpec/DescribeClass:
  IgnoredMetadata:
    type:
      - chain
      - class_method
      - instance_method
      - version
