inherit_from: .rubocop_todo.yml

require:
 - rubocop-rake
 - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Layout/LineLength:
  Max: 100

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"
    - "**/spec/**/*"

Naming/MemoizedInstanceVariableName:
  Enabled: false

# NestedGroups:
#   Max: 5

RSpec/DescribeClass:
  IgnoredMetadata:
    type:
      - chain
      - class_method
      - instance_method
      - version

RSpec/NestedGroups:
  Max: 6

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
