inherit_from: .rubocop_todo.yml

require:
 - rubocop-rake
 - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Layout/LineLength:
  Max: 100

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"
    - "**/spec/**/*"

Naming/MemoizedInstanceVariableName:
  Enabled: false

RSpec/DescribeClass:
  IgnoredMetadata:
    type:
      - chain
      - class_method
      - instance_method
      - version

RSpec/FilePath:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/NestedGroups:
  Max: 7

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/MethodCallWithArgsParentheses:
  Enabled: true
  AllowedMethods:
    - raise
    - to
    - not_to

Style/MultilineBlockChain:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
