source 'https://rubygems.org'

gem 'rake'

# # TODO: address!
# %w[rspec-core rspec-expectations rspec-mocks rspec-support].each do |lib|
#   gem lib, :path => File.expand_path("../../#{lib}", __FILE__)
# end
