source 'https://rubygems.org'

gemspec

%w[core access ingestion validation].each do |lib_suffix|
  lib = "intention-#{lib_suffix}"
  library_path = File.expand_path("../#{lib}", __dir__)

  gem lib, path: library_path
end
