# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

%w[intention-core intention-default intention-null].each do |lib|
  library_path = File.expand_path("../../#{lib}", __FILE__)

  gem lib, path: library_path
end
