source 'https://rubygems.org'

gemspec

%w[support core access].each do |lib_suffix|
  lib = "intention-#{lib_suffix}"
  library_path = File.expand_path("../#{lib}", __dir__)

  # puts "Found #{lib}" if File.exists?(library_path)

  gem lib, path: library_path
end

# # TODO?
# branch = File.read(File.expand_path('maintenance-branch', __dir__)).chomp
# %w[rspec rspec-core rspec-expectations rspec-support].each do |lib|
#   library_path = File.expand_path("../#{lib}", __dir__)
#   if File.exist?(library_path) && !ENV['USE_GIT_REPOS']
#     gem lib, :path => library_path
#   else
#     gem lib, :git => "https://github.com/rspec/#{lib}.git", :branch => branch
#   end
# end

group :development do
  gem 'rspec', '~> 3.4'
end
