source 'https://rubygems.org'

gemspec

%w[support core].each do |lib_suffix|
  lib = "intention-#{lib_suffix}"
  library_path = File.expand_path("../#{lib}", __dir__)

  gem lib, path: library_path
end

group :development do
  gem 'rspec', '~> 3.4'
end
