source 'https://rubygems.org'

gemspec

%w[intention-core].each do |lib|
  library_path = File.expand_path("../../#{lib}", __FILE__)

  # puts "Found #{lib}" if File.exists?(library_path)

  gem lib, path: library_path
end

# branch = File.read(File.expand_path("../maintenance-branch", __FILE__)).chomp
# %w[rspec rspec-core rspec-expectations rspec-support].each do |lib|
#   library_path = File.expand_path("../../#{lib}", __FILE__)
#   if File.exist?(library_path) && !ENV['USE_GIT_REPOS']
#     gem lib, :path => library_path
#   else
#     gem lib, :git => "https://github.com/rspec/#{lib}.git", :branch => branch
#   end
# end

group :development do
  gem 'rake', '~> 13.0'
  gem 'rspec', '~> 3.4'
end
